networks:
  global_site_network:
    driver: bridge

services:
  spring:
    image: ubuntu:latest
    volumes:
      - ./setup.sh:/setup.sh
      - ../../../Global-Site/:/root/Projects/Global-Site/
    command: tail -f /dev/null
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - global_site_network

  mysql:
    image: mysql:latest
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped
    volumes:
      - ./GlobalSite.sql:/sql_files/GlobalSite.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - global_site_network

volumes:
  mysql_data: