# docker-compose up -d
# docker-compose exec spring bash
# /setup.sh

# If 8080 already in use :
# netstat -aon | findstr :8080
# tasklist | findstr [PID]

# If setup.sh is not executable :
# In container terminal :
# apt-get update && apt-get install -y dos2unix && cp /setup.sh /setup-copy.sh && dos2unix /setup-copy.sh && /setup-copy.sh

networks:
  mysql_default:
    external: true

services:
  spring:
    image: ubuntu:latest
    volumes:
      - ./setup.sh:/setup.sh
      - ../../../Global-Site/:/root/Projects/Global-Site/
    command: tail -f /dev/null
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - mysql_default